apiVersion: v1
kind: Pod
metadata:
  name: task3
  labels:
    task: task3 
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'sleep 10000']
    volumeMounts:
    - mountPath: /data
      name: cache-volume
  initContainers:
  - name: init-file
    image: busybox
    command: ['sh', '-c', "touch /data/runfile.txt"]
    volumeMounts:
    - mountPath: /data
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
