apiVersion: v1
kind: Pod
metadata:
  name: lab10-nginx
  labels:
    lab: lab10
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: lab10-busybox
  namespace: securens
  labels:
     lab: lab10-sec
spec:
  containers:
  - name: busybox
    command: ['sh', '-c', 'sleep 3600']
    image: busybox
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lab10
  namespace: default
spec:
  podSelector:
    matchLabels:
      lab: lab10
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          lab: lab10-sec
