apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab6
  labels:
    app: lab6
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab6
  template:
    metadata:
      labels:
        app: lab6
    spec:
      containers:
      - name: nginx
        image: nginx:1.14
