apiVersion: v1
kind: Pod
metadata:
  name: lab7
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      env:
        # Define the environment variable
        - name: myuser # Notice that the case is different here
          valueFrom:
            configMapKeyRef:
              name: lab7           # The ConfigMap this value comes from.
              key: myuser # The key to fetch.

